In [2]:
import pandas as pd
from sqlalchemy import create_engine

# Substitua pelas suas credenciais reais se forem diferentes
DATABASE_URL = "postgresql://admin:password@localhost:5432/spacex_db"
engine = create_engine(DATABASE_URL)
print("✅ Conexão estabelecida.")

✅ Conexão estabelecida.

In [3]:
print("--- Camada Bronze: Amostra de Lançamentos Crus ---")
df_bronze = pd.read_sql("SELECT id, name, success, ingestion_timestamp FROM raw.spacex_launches LIMIT 5", engine)
display(df_bronze)

--- Camada Bronze: Amostra de Lançamentos Crus ---

                         id         name  success        ingestion_timestamp
0  5eb87cd9ffd86e000604b32a    FalconSat    False 2026-03-12 16:29:45.292828
1  5eb87cdaffd86e000604b32b      DemoSat    False 2026-03-12 16:29:45.292828
2  5eb87cdbffd86e000604b32c  Trailblazer    False 2026-03-12 16:29:45.292828
3  5eb87cdbffd86e000604b32d       RatSat     True 2026-03-12 16:29:45.292828
4  5eb87cdcffd86e000604b32e     RazakSat     True 2026-03-12 16:29:45.292828

In [4]:
print("--- Camada Silver: Eventos Solares (NASA) Limpos ---")
# Validando se o startTime foi mapeado corretamente após nossa correção
df_nasa_silver = pd.read_sql("SELECT * FROM public.stg_nasa__solar_events LIMIT 5", engine)
display(df_nasa_silver)

--- Camada Silver: Eventos Solares (NASA) Limpos ---

,activityid,catalog_source,event_at_utc,speed_km_s,cme_type,half_angle,is_most_accurate,source_location,event_description,ingested_at
0,2026-02-10T09:48:00-CME-001,M2M_CATALOG,2026-02-10 09:48:00,319.0,S,10.0,True,N11E67,CME first seen to the NE by SOHO LASCO C2 begi...,2026-03-12 16:29:53.424776
1,2026-02-10T19:38:00-CME-001,M2M_CATALOG,2026-02-10 19:38:00,537.0,C,10.0,True,,This narrow CME is faintly seen to the SW in S...,2026-03-12 16:29:53.424776
2,2026-02-11T03:48:00-CME-001,M2M_CATALOG,2026-02-11 03:48:00,468.0,S,22.0,True,,This CME is visible to the northwest in SOHO L...,2026-03-12 16:29:53.424776
3,2026-02-11T10:08:00-CME-001,M2M_CATALOG,2026-02-11 10:08:00,469.0,S,16.0,True,N17W128,This CME is visible to the northwest in STEREO...,2026-03-12 16:29:53.424776
4,2026-02-11T16:23:00-CME-001,M2M_CATALOG,2026-02-11 16:23:00,309.0,S,16.0,True,,This CME is visible to the north in STEREO A C...,2026-03-12 16:29:53.424776

In [5]:
print("\n--- Camada Silver: Rockets (Tipagem corrigida) ---")
df_rockets_silver = pd.read_sql("SELECT rocket_name, cost_per_launch_usd, success_rate_pct FROM public.stg_spacex__rockets", engine)
display(df_rockets_silver)

--- Camada Silver: Rockets (Tipagem corrigida) ---

    rocket_name  cost_per_launch_usd  success_rate_pct
0      Falcon 1            6700000.0                40
1      Falcon 9           50000000.0                98
2  Falcon Heavy           90000000.0               100
3      Starship            7000000.0                 0

In [6]:
print("--- Camada Gold: Performance de Lançamentos ---")
df_perf = pd.read_sql("SELECT * FROM public_gold.fct_launches_performance LIMIT 5", engine)
display(df_perf)

--- Camada Gold: Performance de Lançamentos ---

,launch_id,launch_name,launch_at_utc,rocket_name,cost_per_launch_usd,total_payload_mass_kg,usd_per_kg,count_cme_events,peak_cme_speed,mission_risk_profile
0,5eb87cdbffd86e000604b32d,RatSat,2008-09-28 23:15:00,Falcon 1,6700000.0,165.0,40606.060606,0,0.0,LOW RISK
1,5eb87cdcffd86e000604b32e,RazakSat,2009-07-13 03:35:00,Falcon 1,6700000.0,200.0,33500.000000,0,0.0,LOW RISK
2,5eb87cddffd86e000604b32f,Falcon 9 Test Flight,2010-06-04 18:45:00,Falcon 9,50000000.0,NaN,0.000000,0,0.0,LOW RISK
3,5eb87cdeffd86e000604b330,COTS 1,2010-12-08 15:43:00,Falcon 9,50000000.0,NaN,0.000000,0,0.0,LOW RISK
4,5eb87cdfffd86e000604b331,COTS 2,2012-05-22 07:44:00,Falcon 9,50000000.0,525.0,95238.095238,0,0.0,LOW RISK

In [7]:

print("\n--- Camada Gold: ROI e Eficiência (Custo por KG) ---")
# Esta é a tabela que corrigimos o JOIN e o Unnest
df_roi = pd.read_sql("SELECT * FROM public_gold.fct_spacex_launch_roi ORDER BY usd_per_kg ASC limit 5", engine)
display(df_roi)

--- Camada Gold: ROI e Eficiência (Custo por KG) ---

,launch_id,rocket_name,total_payload_mass_kg,cost_per_launch_usd,usd_per_kg
0,5ed9819a1f30554030d45c29,Falcon 9,15712.0,50000000.0,3182.281059
1,60e3bf0d73359e1e20335c37,Falcon 9,15600.0,50000000.0,3205.128205
2,5ef6a2090059c33cee4a828b,Falcon 9,15600.0,50000000.0,3205.128205
3,5fbfecfe54ceb10a5664c80b,Falcon 9,15600.0,50000000.0,3205.128205
4,605b4b7daa5433645e37d040,Falcon 9,15600.0,50000000.0,3205.128205

In [12]:
print("--- Camada Gold: Correlação SpaceX vs Clima Espacial (NASA) ---")
df_impact = pd.read_sql("SELECT * FROM public_gold.fct_space_weather_impact WHERE solar_event_id IS NOT NULL", engine)

if df_impact.empty:
    print("Zero correlações diretas (24h) encontradas para o período.")
else:
    print(f"Encontrados {len(df_impact)} lançamentos sob influência de eventos solares!")
    display(df_impact.sort_values('hours_diff'))

--- Camada Gold: Correlação SpaceX vs Clima Espacial (NASA) ---
Zero correlações diretas (24h) encontradas para o período.

In [13]:
# Verificando a janela temporal de cada fonte
query_check = """
    SELECT 
        'SpaceX' as fonte, 
        MIN(launch_at_utc) as data_minima, 
        MAX(launch_at_utc) as data_maxima,
        COUNT(*) as total_registros
    FROM public.stg_spacex__launches
    UNION ALL
    SELECT 
        'NASA' as fonte, 
        MIN(event_at_utc) as data_minima, 
        MAX(event_at_utc) as data_maxima,
        COUNT(*) as total_registros
    FROM public.stg_nasa__solar_events
"""
df_check = pd.read_sql(query_check, engine)
display(df_check)

    fonte         data_minima         data_maxima  total_registros
0  SpaceX 2006-03-24 22:30:00 2022-12-05 00:00:00              205
1    NASA 2026-02-10 09:48:00 2026-03-11 09:38:00              133